"""Smoke + structural tests for the sidtrace tool.

Runs sidtrace on a tiny, self-contained PSID (generated by make_test_sid.py,
no HVSC / no network) and asserts both output artifacts are structurally
valid:

  - .sidwr.bin and .bus.bin exist and have whole records
  - cycles are monotonically non-decreasing (PHI1-stamped)
  - every SID write lands in $D400-$D418 with reg == addr & 0x1F, reg <= 24
  - the bus trace contains the SID writes as a subset (rw=1, $D4xx)
  - meta counts agree with the file sizes

The sidtrace binary path is taken from the SIDTRACE_BIN env var (set by the
Makefile / CI) or defaults to the in-repo build location.
"""
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from sidtrace_records import (  # noqa: E402
    BUS_DT,
    SIDWR_DT,
    load_bus,
    load_sidwr,
    parse_meta,
)

NFRAMES = 50


def _sidtrace_bin():
    cand = os.environ.get("SIDTRACE_BIN") or str(ROOT / "build" / "sidtrace")
    p = Path(cand)
    if not p.exists():
        pytest.skip(f"sidtrace binary not built at {p} (run `make`)")
    return str(p)


@pytest.fixture(scope="session")
def fixture_sid(tmp_path_factory):
    d = tmp_path_factory.mktemp("sid")
    sid = d / "fixture.sid"
    subprocess.run(
        [sys.executable, str(HERE / "make_test_sid.py"), str(sid)],
        check=True,
    )
    assert sid.stat().st_size > 0
    return sid


@pytest.fixture(scope="session")
def trace(tmp_path_factory, fixture_sid):
    d = tmp_path_factory.mktemp("trace")
    prefix = d / "out"
    subprocess.run(
        [_sidtrace_bin(), str(fixture_sid), "1", str(NFRAMES), str(prefix)],
        check=True,
    )
    return {
        "prefix": prefix,
        "sidwr": Path(f"{prefix}.sidwr.bin"),
        "bus": Path(f"{prefix}.bus.bin"),
        "meta": Path(f"{prefix}.meta.txt"),
    }


def test_artifacts_exist(trace):
    assert trace["sidwr"].exists(), "missing .sidwr.bin"
    assert trace["bus"].exists(), "missing .bus.bin"
    assert trace["meta"].exists(), "missing .meta.txt"


def test_record_sizes_are_whole(trace):
    assert trace["sidwr"].stat().st_size % SIDWR_DT.itemsize == 0
    assert trace["bus"].stat().st_size % BUS_DT.itemsize == 0


def test_sid_writes_present_and_in_range(trace):
    sw = load_sidwr(trace["sidwr"])
    assert sw.size > 0, "no SID writes recorded"
    # The fixture writes $D400, $D401, $D404, $D418 every frame.
    assert sw["addr"].min() >= 0xD400
    assert sw["addr"].max() <= 0xD418, "fixture writes only $D400-$D418"
    # reg == addr & 0x1F, and dump contract keeps regs 0..24.
    assert np.all(sw["reg"] == (sw["addr"] & 0x1F))
    assert sw["reg"].max() <= 24
    # the four distinct registers the fixture touches
    assert set(np.unique(sw["reg"]).tolist()) == {0x00, 0x01, 0x04, 0x18}


def test_sidwr_cycles_monotonic(trace):
    sw = load_sidwr(trace["sidwr"])
    assert np.all(np.diff(sw["cycle"]) >= 0), "sidwr cycles not monotonic"


def test_bus_cycles_monotonic(trace):
    bus = load_bus(trace["bus"])
    assert bus.size > 0
    assert np.all(np.diff(bus["cycle"]) >= 0), "bus cycles not monotonic"
    assert set(np.unique(bus["rw"]).tolist()) <= {0, 1}


def test_bus_contains_sid_writes(trace):
    """Every SID write must appear in the full bus trace (it is a subset)."""
    sw = load_sidwr(trace["sidwr"])
    bus = load_bus(trace["bus"])
    sid_writes_in_bus = bus[
        (bus["rw"] == 1) & (bus["addr"] >= 0xD400) & (bus["addr"] <= 0xD7FF)
    ]
    assert sid_writes_in_bus.size == sw.size, (
        f"bus has {sid_writes_in_bus.size} SID writes, "
        f"sidwr has {sw.size}"
    )
    # cycle/addr/val of the SID-write subset match the sidwr log
    assert np.array_equal(sid_writes_in_bus["cycle"], sw["cycle"])
    assert np.array_equal(sid_writes_in_bus["addr"], sw["addr"])
    assert np.array_equal(sid_writes_in_bus["val"], sw["val"])


def test_meta_counts_match_files(trace):
    meta = parse_meta(trace["meta"])
    sw = load_sidwr(trace["sidwr"])
    bus = load_bus(trace["bus"])
    assert int(meta["n_sid_writes"]) == sw.size
    assert int(meta["n_bus_accesses"]) == bus.size
    assert meta["format"].startswith("PlaySID")
    assert int(meta["cycles_per_frame"]) > 0


def test_per_frame_write_cadence(trace):
    """The fixture issues a fixed set of writes each frame; check it scales
    with the requested frame count (a coarse correctness signal).

    The play routine writes 4 registers ($D400/$D401/$D404/$D418) per frame.
    The number of frames actually clocked is governed by the tune's IRQ
    cadence over the requested cycle budget, so allow generous slack while
    still confirming the count tracks NFRAMES rather than being trivial.
    """
    sw = load_sidwr(trace["sidwr"])
    writes_per_frame = 4
    # At least ~80% of NFRAMES worth of frames should be present, and not
    # wildly more than NFRAMES+a couple of frames of slack.
    assert sw.size >= writes_per_frame * int(NFRAMES * 0.8)
    assert sw.size <= writes_per_frame * (NFRAMES + 3)
    # The frame counter ($D400 value) advances monotonically each frame,
    # proving RAM state is being threaded through the player (bus-observable).
    d400 = sw[sw["reg"] == 0x00]
    assert d400.size >= int(NFRAMES * 0.8)
    assert np.all(np.diff(d400["val"].astype(np.int16)) >= 0) or (
        # wraps at 256; allow a single wrap discontinuity
        np.sum(np.diff(d400["val"].astype(np.int16)) < 0) <= 1
    )
