"""Smoke + structural tests for the sidtrace tool.

Runs sidtrace on a tiny, self-contained PSID (generated by make_test_sid.py,
no HVSC / no network) and asserts both output artifacts are structurally valid:

  - .sidwr.bin and .distill.bin exist; sidwr has whole 12-byte records
  - sidwr cycles are monotonically non-decreasing (PHI1-stamped)
  - every SID write lands in $D400-$D418 with reg == addr & 0x1F, reg <= 24
  - the SDST distill artifact parses, carries a sane access-type map, a song-data
    snapshot, and the PC-tagged SID-write summary (and stays a few KB)
  - meta counts agree with the files

The cycle-by-cycle bus trace is RETIRED -- sidtrace distills the run in the
emulator and emits the compact SDST artifact instead (no multi-GB stream).

The sidtrace binary path is taken from the SIDTRACE_BIN env var (set by the
Makefile / CI) or defaults to the in-repo build location.
"""

import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from sidtrace_records import (  # noqa: E402
    ACC_EXEC_PLAY,
    ACC_READ_PLAY,
    ACC_WRITE_PLAY,
    ALU_INC,
    LK_IMMEDIATE,
    LK_STATE_CELL,
    SIDWR_DT,
    load_sidwr,
    parse_meta,
    parse_sdst,
)

NFRAMES = 50


def _sidtrace_bin():
    cand = os.environ.get("SIDTRACE_BIN") or str(ROOT / "build" / "sidtrace")
    p = Path(cand)
    if not p.exists():
        pytest.skip(f"sidtrace binary not built at {p} (run `make`)")
    return str(p)


@pytest.fixture(scope="session")
def fixture_sid(tmp_path_factory):
    d = tmp_path_factory.mktemp("sid")
    sid = d / "fixture.sid"
    subprocess.run(
        [sys.executable, str(HERE / "make_test_sid.py"), str(sid)],
        check=True,
    )
    assert sid.stat().st_size > 0
    return sid


@pytest.fixture(scope="session")
def trace(tmp_path_factory, fixture_sid):
    d = tmp_path_factory.mktemp("trace")
    prefix = d / "out"
    subprocess.run(
        [_sidtrace_bin(), str(fixture_sid), "1", str(NFRAMES), str(prefix)],
        check=True,
    )
    return {
        "prefix": prefix,
        "sidwr": Path(f"{prefix}.sidwr.bin"),
        "distill": Path(f"{prefix}.distill.bin"),
        "meta": Path(f"{prefix}.meta.txt"),
    }


def test_artifacts_exist(trace):
    assert trace["sidwr"].exists(), "missing .sidwr.bin"
    assert trace["distill"].exists(), "missing .distill.bin"
    assert trace["meta"].exists(), "missing .meta.txt"


def test_sidwr_records_are_whole(trace):
    assert trace["sidwr"].stat().st_size % SIDWR_DT.itemsize == 0


def test_sid_writes_present_and_in_range(trace):
    sw = load_sidwr(trace["sidwr"])
    assert sw.size > 0, "no SID writes recorded"
    assert sw["addr"].min() >= 0xD400
    assert sw["addr"].max() <= 0xD418, "fixture writes only $D400-$D418"
    assert np.all(sw["reg"] == (sw["addr"] & 0x1F))
    assert sw["reg"].max() <= 24
    assert set(np.unique(sw["reg"]).tolist()) == {0x00, 0x01, 0x04, 0x18}


def test_sidwr_cycles_monotonic(trace):
    sw = load_sidwr(trace["sidwr"])
    assert np.all(np.diff(sw["cycle"]) >= 0), "sidwr cycles not monotonic"


def test_distill_is_tiny(trace):
    """The whole point: the per-tune artifact is a few KB, not a multi-GB trace."""
    assert trace["distill"].stat().st_size < 64 * 1024


def test_distill_parses_and_is_well_formed(trace):
    d = parse_sdst(trace["distill"])
    assert d["version"] == 1
    assert d["cycles_per_frame"] > 0
    # The access-type map saw code execution (the player ran) and data writes.
    assert (d["acc"] & ACC_EXEC_PLAY).any(), "no code executed during play"
    assert (d["acc"] & ACC_WRITE_PLAY).any(), "no data written during play"
    # The PC-tagged SID-write summary attributes writes to code sites.
    assert d["sid_writes"], "no PC-tagged SID writes summarised"
    regs = {reg for _pc, reg, _c, _v in d["sid_writes"]}
    assert {0x00, 0x01, 0x04, 0x18} <= regs


def test_distill_sid_summary_matches_sidwr(trace):
    """The PC-tagged SID-write summary's total count equals the sidwr stream."""
    d = parse_sdst(trace["distill"])
    sw = load_sidwr(trace["sidwr"])
    total = sum(c for _pc, _reg, c, _v in d["sid_writes"])
    assert total == sw.size


def test_distill_smc_and_song_data_disjoint(trace):
    """SMC (EXEC & WRITE during play) and song data (READ & not WRITE & not EXEC)
    are classified by access TYPE and never overlap."""
    d = parse_sdst(trace["distill"])
    acc = d["acc"]
    smc = ((acc & ACC_EXEC_PLAY) != 0) & ((acc & ACC_WRITE_PLAY) != 0)
    exec_any = (acc & ACC_EXEC_PLAY) != 0
    song = ((acc & ACC_READ_PLAY) != 0) & ((acc & ACC_WRITE_PLAY) == 0) & ~exec_any
    assert not (smc & song).any()


def test_meta_counts_match_files(trace):
    meta = parse_meta(trace["meta"])
    sw = load_sidwr(trace["sidwr"])
    assert int(meta["n_sid_writes"]) == sw.size
    assert meta["artifact"] == "SDST"
    assert int(meta["distill_bytes"]) == trace["distill"].stat().st_size
    assert meta["format"].startswith("PlaySID")
    assert int(meta["cycles_per_frame"]) > 0


def _trace_to(prefix, fixture_sid, env=None):
    run_env = dict(os.environ)
    if env:
        run_env.update(env)
    subprocess.run(
        [_sidtrace_bin(), str(fixture_sid), "1", str(NFRAMES), str(prefix)],
        check=True,
        env=run_env,
    )
    return Path(f"{prefix}.sidwr.bin"), Path(f"{prefix}.distill.bin")


def test_deterministic_byte_identical(tmp_path, fixture_sid):
    """Tracing the same tune twice must produce byte-identical artifacts.

    libsidplayfp's default powerOnDelay is the random-delay sentinel, seeded from
    the wall clock; sidtrace pins it so the C64 start state is fixed. This guards
    that both the .sidwr.bin and the .distill.bin are reproducible run-to-run.
    """
    sw_a, dist_a = _trace_to(tmp_path / "a", fixture_sid)
    sw_b, dist_b = _trace_to(tmp_path / "b", fixture_sid)
    assert sw_a.read_bytes() == sw_b.read_bytes(), ".sidwr.bin not deterministic"
    assert dist_a.read_bytes() == dist_b.read_bytes(), ".distill.bin not deterministic"


def test_deterministic_over_many_runs(tmp_path, fixture_sid):
    """Stronger determinism guard: the sidwr + distill digests are identical
    across many runs (the original bug surfaced as a *sometimes* short capture, so
    a single repeat can miss it)."""
    import hashlib

    digests = set()
    for i in range(5):
        sw, dist = _trace_to(tmp_path / f"r{i}", fixture_sid)
        digests.add(
            (
                hashlib.sha256(sw.read_bytes()).hexdigest(),
                hashlib.sha256(dist.read_bytes()).hexdigest(),
            )
        )
    assert len(digests) == 1, f"non-deterministic over 5 runs: {digests}"


def test_siddf_present_and_keyed_by_pc_reg(trace):
    """The per-write data-flow summary (SIDDF) exists and shares SIDW's (PC,reg)
    key space -- it is O(code sites), not O(frames)."""
    d = parse_sdst(trace["distill"])
    assert d["siddf"], "no SIDDF data-flow summaries emitted"
    sidw_keys = {(pc, reg) for pc, reg, _c, _v in d["sid_writes"]}
    siddf_keys = {(e["pc"], e["reg"]) for e in d["siddf"]}
    # every data-flow site corresponds to a real SID-write site
    assert siddf_keys <= sidw_keys
    # the regs covered include the fixture's distinct write registers
    assert {0x00, 0x01, 0x04, 0x18} <= {e["reg"] for e in d["siddf"]}


def test_siddf_classifies_state_vs_constant(trace):
    """The fixture's freq-lo ($D400) is loaded from a RAM counter that is
    INC'd every play-call -> its slice leaf must be a STATE_CELL (read+write
    during play), NOT a constant. The immediate-loaded registers (#$11 ->
    $D401, #$21 -> $D404, #$0F -> $D418) must surface an IMMEDIATE leaf and a
    constant value range (val_lo == val_hi)."""
    d = parse_sdst(trace["distill"])
    by_reg = {e["reg"]: e for e in d["siddf"]}

    fr = by_reg[0x00]  # freq-lo, fed by the INC'd counter
    leaf_kinds = {k for k, _a, _v in fr["leaves"]}
    assert LK_STATE_CELL in leaf_kinds, (
        "freq-lo's counter source must classify as state_cell, not constant"
    )
    # the counter is genuinely mutable -> the written value is not constant
    assert fr["val_lo"] != fr["val_hi"]

    for reg in (0x01, 0x04, 0x18):  # immediate-loaded -> constant
        e = by_reg[reg]
        kinds = {k for k, _a, _v in e["leaves"]}
        assert LK_IMMEDIATE in kinds, f"reg {reg:#x} should have an immediate leaf"
        assert e["val_lo"] == e["val_hi"], f"reg {reg:#x} should be constant"


def test_siddf_flat_vs_capture_length(tmp_path, fixture_sid):
    """The decisive length-independence property: the SIDDF section size does NOT
    grow with the number of frames captured (it is keyed by code site). Trace a
    short and a long window and require the SIDDF byte count to be identical."""

    def siddf_nbytes(distill_path):
        buf = distill_path.read_bytes()
        i = buf.find(b"SDDF")
        assert i >= 0
        # SDDF is followed by STSQ then END; measure to whichever comes first so
        # the SIDDF size is isolated from the (separately-bounded) STSQ section.
        j = buf.find(b"STSQ", i)
        if j < 0:
            j = buf.find(b"END\x00", i)
        return (j if j >= 0 else len(buf)) - i

    def trace_n(prefix, n):
        subprocess.run(
            [_sidtrace_bin(), str(fixture_sid), "1", str(n), str(prefix)],
            check=True,
        )
        return Path(f"{prefix}.distill.bin")

    short = trace_n(tmp_path / "short", 30)
    long = trace_n(tmp_path / "long", 600)
    sw_short = load_sidwr(Path(str(short).replace(".distill.bin", ".sidwr.bin")))
    sw_long = load_sidwr(Path(str(long).replace(".distill.bin", ".sidwr.bin")))
    assert sw_long.size > sw_short.size * 5, "long capture should have many more writes"
    assert siddf_nbytes(short) == siddf_nbytes(long), (
        "SIDDF size grew with capture length -- it must be O(code sites), not O(frames)"
    )


def test_stateseq_present_for_flagged_state_cells(trace):
    """STATESEQ (design 3.2) carries an inter-frame sample sequence for every cell
    SIDDF flagged as a state leaf. The fixture's freq-lo ($D400) is fed by a RAM
    counter INC'd every play-call; that counter must appear in STATESEQ with a
    monotone +1 sample sequence (and holds_to_end True -- a constant-stride
    accumulator)."""
    d = parse_sdst(trace["distill"])
    assert d["stateseq"], "no STATESEQ sample sequences emitted"
    # the set of STATESEQ cells must be exactly the SIDDF-flagged state cells
    siddf_state = {
        a for e in d["siddf"] for k, a, _v in e["leaves"] if k == LK_STATE_CELL
    }
    stseq_addrs = {e["addr"] for e in d["stateseq"]}
    assert stseq_addrs == siddf_state, (
        f"STATESEQ cells {sorted(stseq_addrs)} != SIDDF state cells "
        f"{sorted(siddf_state)}"
    )
    # the counter cell's sequence is a clean +1 accumulator -> holds_to_end.
    counter = next(e for e in d["stateseq"] if e["holds_to_end"])
    s = counter["samples"]
    assert len(s) >= 8
    diffs = {(s[i + 1] - s[i]) & 0xFF for i in range(len(s) - 1)}
    assert diffs == {1}, f"counter STATESEQ is not a +1 accumulator: diffs={diffs}"


def test_stateseq_bounded_and_flat_vs_capture_length(tmp_path, fixture_sid):
    """STATESEQ stays bounded (capped at M samples/cell) and does NOT grow once
    the capture window exceeds M and all state cells are discovered: the section is
    O(state cells * M), not O(frames). Trace two windows both >> M and require an
    identical STATESEQ byte count."""

    def stsq_nbytes(distill_path):
        buf = distill_path.read_bytes()
        i = buf.find(b"STSQ")
        assert i >= 0, "no STSQ section"
        # STSQ is followed by SDCU then END; measure to whichever comes first so the
        # STSQ size is isolated from the (separately-bounded) SDCU section.
        j = buf.find(b"SDCU", i)
        if j < 0:
            j = buf.find(b"END\x00", i)
        return (j if j >= 0 else len(buf)) - i

    def trace_n(prefix, n):
        subprocess.run(
            [_sidtrace_bin(), str(fixture_sid), "1", str(n), str(prefix)],
            check=True,
        )
        return Path(f"{prefix}.distill.bin")

    # both windows exceed M=512 so the per-cell sample count is saturated and the
    # fixture's single state cell is discovered immediately -> identical size.
    a = trace_n(tmp_path / "w800", 800)
    b = trace_n(tmp_path / "w1600", 1600)
    sw_a = load_sidwr(Path(str(a).replace(".distill.bin", ".sidwr.bin")))
    sw_b = load_sidwr(Path(str(b).replace(".distill.bin", ".sidwr.bin")))
    assert sw_b.size > sw_a.size, "longer capture should have more SID writes"
    assert stsq_nbytes(a) == stsq_nbytes(b), (
        "STATESEQ size grew with capture length -- it must be O(state cells * M)"
    )
    # and the per-cell sample count is capped at M=512.
    d = parse_sdst(b)
    assert all(e["n_samples"] <= 512 for e in d["stateseq"])


def test_sdcu_present_for_state_cell_update(trace):
    """SDCU (design 2.2/2.3) carries the in-call UPDATE DAG of each state cell -- how
    the cell was recomputed, the data the SID-write slice could not give (the cell is
    a leaf there). The fixture's RAM counter is INC'd every play-call; its SDCU entry
    must be the self-feedback accumulator recurrence s' = s+1: an INC op with the cell
    itself as a (state) leaf. Keyed by the cell ADDRESS, so O(state cells)."""
    d = parse_sdst(trace["distill"])
    assert d["sdcu"], "no SDCU update DAGs emitted"
    # every SDCU cell is a SIDDF-flagged state cell (the emit filter)
    siddf_state = {
        a for e in d["siddf"] for k, a, _v in e["leaves"] if k == LK_STATE_CELL
    }
    sdcu_addrs = {e["pc"] for e in d["sdcu"]}   # pc field holds the cell addr
    assert sdcu_addrs <= siddf_state, (
        f"SDCU cells {sorted(sdcu_addrs)} must be SIDDF state cells "
        f"{sorted(siddf_state)}"
    )
    # the counter cell's update DAG is the s'=s+1 accumulator: INC + self-leaf.
    counter = next(iter(d["sdcu"]))
    assert ALU_INC in counter["op_seq"], (
        f"counter update DAG is not an INC accumulator: ops={counter['op_seq']}"
    )
    assert any(a == counter["pc"] for _k, a, _v in counter["leaves"]), (
        "the accumulator's own cell must be a self-feedback leaf of its update"
    )


def test_sdcu_carries_midcall_valseq(trace):
    """Stage 3b: every SDCU entry carries the cell's MID-CALL value sequence (the
    value its in-call UPDATE wrote, sampled at the update site -- NOT at the call
    boundary). This is the genuine generator state stream the host feeds to
    Berlekamp-Massey for the LFSR-vs-not verdict (a fast SMC cell's call-boundary
    STATESEQ is a constant residue and useless for that). It must be present and
    bounded; for the fixture's INC counter it is the running counter value."""
    d = parse_sdst(trace["distill"])
    assert d["sdcu"], "no SDCU update DAGs emitted"
    for e in d["sdcu"]:
        vs = e.get("val_seq", [])
        assert isinstance(vs, list)
        assert len(vs) <= 512, "SDCU value sequence exceeds the bound"
    # at least one SDCU cell carries a non-trivial value sequence (the counter)
    assert any(len(e.get("val_seq", [])) >= 2 for e in d["sdcu"]), (
        "no SDCU cell carried a mid-call value sequence"
    )


def test_sddf_has_no_valseq(trace):
    """The mid-call value sequence is an SDCU-only field; SDDF (the SID-write
    slices) writes nValSeq=0 (the field exists only for a uniform entry shape so one
    reader parses both sections)."""
    d = parse_sdst(trace["distill"])
    for e in d["siddf"]:
        assert not e.get("val_seq", []), "SDDF must not carry a value sequence"


def test_sdcu_flat_vs_capture_length(tmp_path, fixture_sid):
    """SDCU is O(state cells) + a BOUNDED per-cell mid-call value sequence, NOT
    O(frames): the update DAG of a cell (op_seq + leaves + strided interval) is
    invariant across frames, and the mid-call value sequence is capped at
    SDCU_VALSEQ_M (512) samples per cell. So (a) the STRUCTURAL part of each SDCU
    entry is byte-identical across capture lengths and (b) the value sequence
    SATURATES at the cap and stops growing -- it is flat, not length-proportional.

    (Stage 3b: the value sequence is the genuine mid-call generator state stream the
    host feeds to Berlekamp-Massey; it is bounded so the artifact stays flat.)"""

    SDCU_VALSEQ_M = 512  # mirror SiddfSummary::SDCU_VALSEQ_M

    def sdcu_entries(distill_path):
        d = parse_sdst(distill_path)
        # key by cell addr; record (structural-signature, valseq-len)
        out = {}
        for e in d["sdcu"]:
            struct_sig = (
                tuple(e["op_seq"]), tuple(e["leaves"]), e["has_stride"],
                e["stride_base"], e["stride_idx_min"], e["stride_idx_max"],
            )
            out[e["pc"]] = (struct_sig, len(e.get("val_seq", [])))
        return out

    def trace_n(prefix, n):
        subprocess.run(
            [_sidtrace_bin(), str(fixture_sid), "1", str(n), str(prefix)],
            check=True,
        )
        return Path(f"{prefix}.distill.bin")

    # two windows both well PAST value-sequence saturation (the per-cell cap is
    # reached early), so the value-sequence length is identical too.
    a = sdcu_entries(trace_n(tmp_path / "s_a", 1200))
    b = sdcu_entries(trace_n(tmp_path / "s_b", 2400))
    common = set(a) & set(b)
    assert common, "no common SDCU cells across capture lengths"
    for addr in common:
        # STRUCTURAL part is invariant (the update DAG is the recurrence)
        assert a[addr][0] == b[addr][0], (
            f"SDCU update DAG of ${addr:04x} changed with capture length"
        )
        # value sequence is bounded by the cap and (past saturation) does not grow
        assert a[addr][1] <= SDCU_VALSEQ_M and b[addr][1] <= SDCU_VALSEQ_M
        assert a[addr][1] == b[addr][1], (
            f"SDCU value sequence of ${addr:04x} grew with capture length past "
            f"saturation -- must be bounded/flat: {a[addr][1]} vs {b[addr][1]}"
        )


def test_per_frame_write_cadence(trace):
    """The fixture issues a fixed set of writes each frame; check it scales with
    the requested frame count (a coarse correctness signal)."""
    sw = load_sidwr(trace["sidwr"])
    writes_per_frame = 4
    assert sw.size >= writes_per_frame * int(NFRAMES * 0.8)
    assert sw.size <= writes_per_frame * (NFRAMES + 3)
    d400 = sw[sw["reg"] == 0x00]
    assert d400.size >= int(NFRAMES * 0.8)
    assert np.all(np.diff(d400["val"].astype(np.int16)) >= 0) or (
        np.sum(np.diff(d400["val"].astype(np.int16)) < 0) <= 1
    )


# --------------------------------------------------------------------------- #
# Stage 5 -- the SELF-MODIFYING-OPERAND axis class (the DefMon compiled-player
# shape). DefMon generates every axis as `LDX #lo / STX $D4xx` whose `#lo` operand
# byte is poked each play-call. Before the Stage-5 fix the SID-write slice bottomed
# out at that immediate as a CONSTANT, so DefMon emitted ZERO SDCU and ZERO STATESEQ
# (the host got none of the structure it gets for JCH). The fix classifies a
# self-modified immediate operand as a state cell at the operand address (deferred
# to finalizeLeaves so the per-call WRITE_PLAY is seen), re-enabling SDCU + STATESEQ.
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="session")
def smc_sid(tmp_path_factory):
    d = tmp_path_factory.mktemp("smc_sid")
    sid = d / "smc.sid"
    subprocess.run(
        [sys.executable, str(HERE / "make_smc_operand_sid.py"), str(sid)],
        check=True,
    )
    assert sid.stat().st_size > 0
    return sid


@pytest.fixture(scope="session")
def smc_trace(tmp_path_factory, smc_sid):
    d = tmp_path_factory.mktemp("smc_trace")
    prefix = d / "out"
    subprocess.run(
        [_sidtrace_bin(), str(smc_sid), "1", "200", str(prefix)], check=True
    )
    return {"distill": Path(f"{prefix}.distill.bin")}


def test_smc_operand_surfaced_as_state_cell(smc_trace):
    """The self-modified `LDX #` operand byte ($D400's source) must be a STATE_CELL
    leaf of the SID-write slice -- at the operand ADDRESS -- not an immediate
    constant. This is the Gap-2 root cause: a constant leaf yields no state cell, so
    SDCU/STATESEQ never trigger (design 1.3 SMC / 2.3)."""
    d = parse_sdst(smc_trace["distill"])
    state_addrs = {
        a for e in d["siddf"] for k, a, _v in e["leaves"] if k == LK_STATE_CELL
    }
    assert state_addrs, "SMC operand byte not surfaced as a state cell"
    # the operand byte is EXEC & WRITE during play (the SMC-correct classification).
    for a in state_addrs:
        bits = int(d["acc"][a])
        assert bits & ACC_EXEC_PLAY, f"${a:04x} state cell is not EXEC during play"
        assert bits & ACC_WRITE_PLAY, f"${a:04x} state cell not WRITE during play"


def test_smc_operand_emits_sdcu_and_stateseq(smc_trace):
    """The Gap-2 fix: once the operand is a state cell, its UPDATE slice (SDCU) and
    inter-frame sample sequence (STATESEQ) emit -- the structure the host needs to
    fit a recurrence. Both were ZERO before the fix."""
    d = parse_sdst(smc_trace["distill"])
    assert d["sdcu"], "SMC operand produced no SDCU update DAG (Gap-2 regression)"
    assert d["stateseq"], "SMC operand produced no STATESEQ (Gap-2 regression)"
    # SDCU/STATESEQ cells are exactly the SIDDF-flagged state cells.
    state_addrs = {
        a for e in d["siddf"] for k, a, _v in e["leaves"] if k == LK_STATE_CELL
    }
    assert {e["pc"] for e in d["sdcu"]} <= state_addrs
    assert {e["addr"] for e in d["stateseq"]} <= state_addrs
    # the operand cell's STATESEQ tracks the generator (here a +1 counter walk).
    samples = d["stateseq"][0]["samples"]
    assert len(samples) >= 2 and len(set(samples)) >= 2, (
        "STATESEQ did not capture the operand's inter-frame variation"
    )


def test_smc_operand_artifact_bounded_and_flat(tmp_path, smc_sid):
    """The Gap-2 fix stays bounded/flat vs capture length: the SMC-operand cells'
    SDCU structural part is invariant and STATESEQ saturates at the cap, so the
    artifact does not grow proportionally with frames (design 3 boundedness)."""
    def cells(prefix, n):
        subprocess.run(
            [_sidtrace_bin(), str(smc_sid), "1", str(n), str(prefix)], check=True
        )
        d = parse_sdst(Path(f"{prefix}.distill.bin"))
        sdcu = {
            e["pc"]: (tuple(e["op_seq"]), tuple(e["leaves"]))
            for e in d["sdcu"]
        }
        nstseq = {e["addr"]: e["n_samples"] for e in d["stateseq"]}
        return sdcu, nstseq

    a_sdcu, a_st = cells(tmp_path / "a", 600)
    b_sdcu, b_st = cells(tmp_path / "b", 1200)
    common = set(a_sdcu) & set(b_sdcu)
    assert common, "no common SMC SDCU cells across capture lengths"
    for addr in common:
        assert a_sdcu[addr] == b_sdcu[addr], (
            f"SMC operand ${addr:04x} update DAG changed with capture length"
        )
    for addr in set(a_st) & set(b_st):
        assert a_st[addr] <= 512 and b_st[addr] <= 512, "STATESEQ exceeds the cap"
