"""Smoke + structural tests for the sidtrace tool.

Runs sidtrace on a tiny, self-contained PSID (generated by make_test_sid.py,
no HVSC / no network) and asserts both output artifacts are structurally valid:

  - .sidwr.bin and .distill.bin exist; sidwr has whole 12-byte records
  - sidwr cycles are monotonically non-decreasing (PHI1-stamped)
  - every SID write lands in $D400-$D418 with reg == addr & 0x1F, reg <= 24
  - the SDST distill artifact parses, carries a sane access-type map, a song-data
    snapshot, and the PC-tagged SID-write summary (and stays a few KB)
  - meta counts agree with the files

The cycle-by-cycle bus trace is RETIRED -- sidtrace distills the run in the
emulator and emits the compact SDST artifact instead (no multi-GB stream).

The sidtrace binary path is taken from the SIDTRACE_BIN env var (set by the
Makefile / CI) or defaults to the in-repo build location.
"""

import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from sidtrace_records import (  # noqa: E402
    ACC_EXEC_PLAY,
    ACC_READ_PLAY,
    ACC_WRITE_PLAY,
    SIDWR_DT,
    load_sidwr,
    parse_meta,
    parse_sdst,
)

NFRAMES = 50


def _sidtrace_bin():
    cand = os.environ.get("SIDTRACE_BIN") or str(ROOT / "build" / "sidtrace")
    p = Path(cand)
    if not p.exists():
        pytest.skip(f"sidtrace binary not built at {p} (run `make`)")
    return str(p)


@pytest.fixture(scope="session")
def fixture_sid(tmp_path_factory):
    d = tmp_path_factory.mktemp("sid")
    sid = d / "fixture.sid"
    subprocess.run(
        [sys.executable, str(HERE / "make_test_sid.py"), str(sid)],
        check=True,
    )
    assert sid.stat().st_size > 0
    return sid


@pytest.fixture(scope="session")
def trace(tmp_path_factory, fixture_sid):
    d = tmp_path_factory.mktemp("trace")
    prefix = d / "out"
    subprocess.run(
        [_sidtrace_bin(), str(fixture_sid), "1", str(NFRAMES), str(prefix)],
        check=True,
    )
    return {
        "prefix": prefix,
        "sidwr": Path(f"{prefix}.sidwr.bin"),
        "distill": Path(f"{prefix}.distill.bin"),
        "meta": Path(f"{prefix}.meta.txt"),
    }


def test_artifacts_exist(trace):
    assert trace["sidwr"].exists(), "missing .sidwr.bin"
    assert trace["distill"].exists(), "missing .distill.bin"
    assert trace["meta"].exists(), "missing .meta.txt"


def test_sidwr_records_are_whole(trace):
    assert trace["sidwr"].stat().st_size % SIDWR_DT.itemsize == 0


def test_sid_writes_present_and_in_range(trace):
    sw = load_sidwr(trace["sidwr"])
    assert sw.size > 0, "no SID writes recorded"
    assert sw["addr"].min() >= 0xD400
    assert sw["addr"].max() <= 0xD418, "fixture writes only $D400-$D418"
    assert np.all(sw["reg"] == (sw["addr"] & 0x1F))
    assert sw["reg"].max() <= 24
    assert set(np.unique(sw["reg"]).tolist()) == {0x00, 0x01, 0x04, 0x18}


def test_sidwr_cycles_monotonic(trace):
    sw = load_sidwr(trace["sidwr"])
    assert np.all(np.diff(sw["cycle"]) >= 0), "sidwr cycles not monotonic"


def test_distill_is_tiny(trace):
    """The whole point: the per-tune artifact is a few KB, not a multi-GB trace."""
    assert trace["distill"].stat().st_size < 64 * 1024


def test_distill_parses_and_is_well_formed(trace):
    d = parse_sdst(trace["distill"])
    assert d["version"] == 1
    assert d["cycles_per_frame"] > 0
    # The access-type map saw code execution (the player ran) and data writes.
    assert (d["acc"] & ACC_EXEC_PLAY).any(), "no code executed during play"
    assert (d["acc"] & ACC_WRITE_PLAY).any(), "no data written during play"
    # The PC-tagged SID-write summary attributes writes to code sites.
    assert d["sid_writes"], "no PC-tagged SID writes summarised"
    regs = {reg for _pc, reg, _c, _v in d["sid_writes"]}
    assert {0x00, 0x01, 0x04, 0x18} <= regs


def test_distill_sid_summary_matches_sidwr(trace):
    """The PC-tagged SID-write summary's total count equals the sidwr stream."""
    d = parse_sdst(trace["distill"])
    sw = load_sidwr(trace["sidwr"])
    total = sum(c for _pc, _reg, c, _v in d["sid_writes"])
    assert total == sw.size


def test_distill_smc_and_song_data_disjoint(trace):
    """SMC (EXEC & WRITE during play) and song data (READ & not WRITE & not EXEC)
    are classified by access TYPE and never overlap."""
    d = parse_sdst(trace["distill"])
    acc = d["acc"]
    smc = ((acc & ACC_EXEC_PLAY) != 0) & ((acc & ACC_WRITE_PLAY) != 0)
    exec_any = (acc & ACC_EXEC_PLAY) != 0
    song = ((acc & ACC_READ_PLAY) != 0) & ((acc & ACC_WRITE_PLAY) == 0) & ~exec_any
    assert not (smc & song).any()


def test_meta_counts_match_files(trace):
    meta = parse_meta(trace["meta"])
    sw = load_sidwr(trace["sidwr"])
    assert int(meta["n_sid_writes"]) == sw.size
    assert meta["artifact"] == "SDST"
    assert int(meta["distill_bytes"]) == trace["distill"].stat().st_size
    assert meta["format"].startswith("PlaySID")
    assert int(meta["cycles_per_frame"]) > 0


def _trace_to(prefix, fixture_sid, env=None):
    run_env = dict(os.environ)
    if env:
        run_env.update(env)
    subprocess.run(
        [_sidtrace_bin(), str(fixture_sid), "1", str(NFRAMES), str(prefix)],
        check=True,
        env=run_env,
    )
    return Path(f"{prefix}.sidwr.bin"), Path(f"{prefix}.distill.bin")


def test_deterministic_byte_identical(tmp_path, fixture_sid):
    """Tracing the same tune twice must produce byte-identical artifacts.

    libsidplayfp's default powerOnDelay is the random-delay sentinel, seeded from
    the wall clock; sidtrace pins it so the C64 start state is fixed. This guards
    that both the .sidwr.bin and the .distill.bin are reproducible run-to-run.
    """
    sw_a, dist_a = _trace_to(tmp_path / "a", fixture_sid)
    sw_b, dist_b = _trace_to(tmp_path / "b", fixture_sid)
    assert sw_a.read_bytes() == sw_b.read_bytes(), ".sidwr.bin not deterministic"
    assert dist_a.read_bytes() == dist_b.read_bytes(), ".distill.bin not deterministic"


def test_deterministic_over_many_runs(tmp_path, fixture_sid):
    """Stronger determinism guard: the sidwr + distill digests are identical
    across many runs (the original bug surfaced as a *sometimes* short capture, so
    a single repeat can miss it)."""
    import hashlib

    digests = set()
    for i in range(5):
        sw, dist = _trace_to(tmp_path / f"r{i}", fixture_sid)
        digests.add(
            (
                hashlib.sha256(sw.read_bytes()).hexdigest(),
                hashlib.sha256(dist.read_bytes()).hexdigest(),
            )
        )
    assert len(digests) == 1, f"non-deterministic over 5 runs: {digests}"


def test_per_frame_write_cadence(trace):
    """The fixture issues a fixed set of writes each frame; check it scales with
    the requested frame count (a coarse correctness signal)."""
    sw = load_sidwr(trace["sidwr"])
    writes_per_frame = 4
    assert sw.size >= writes_per_frame * int(NFRAMES * 0.8)
    assert sw.size <= writes_per_frame * (NFRAMES + 3)
    d400 = sw[sw["reg"] == 0x00]
    assert d400.size >= int(NFRAMES * 0.8)
    assert np.all(np.diff(d400["val"].astype(np.int16)) >= 0) or (
        np.sum(np.diff(d400["val"].astype(np.int16)) < 0) <= 1
    )
